#!/usr/bin/env zsh

STOW_FOLDERS="bin,i3,nvim,tmux,ubuntu,zsh"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder -t $HOME
done
popd
