#!/usr/bin/env bash

alias python="python3"
alias vim="$VIM"

alias work="cd ~/work"
alias personal="cd ~/personal"
alias projects="cd ~/projects"
alias vimdir="cd ~/.config/nvim"

alias i3cfg="nvim $XDG_CONFIG_HOME/i3/config"
alias install_dot="zsh /home/cupoftea/.dotfiles/install-ubuntu.sh && source ~/.zshrc"

