#!/usr/bin/env bash
#
alias python="python3"

alias work="cd ~/work"
alias personal="cd ~/personal"
alias projects="cd ~/projects"

alias vim="$VIM"
alias vimc="cd ~/.config/nvim"

alias i3rc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias bdot="dotFileInstall && source ~/.zshrc"
alias dotFileInstall="$DOTFILES/install"

